# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    # Btrfs on LVM or other block devices requires the "btrfs" filesystem
    # to be supported in the initrd.
    initrd.supportedFilesystems = [ "btrfs" ];
    initrd.availableKernelModules = [ "nvme" "xhci_pci" "amdgpu" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [  ];
    # Set the primary ESP mount point, which is required as it's not the default.
    loader.efi.efiSysMountPoint = "/efi";

    # This is the legacy way to ensure multi-device Btrfs arrays are
    # assembled in the initrd. It explicitly waits for both devices to appear.
    # This is more compatible with older NixOS installers.
    initrd.preLVMCommands = ''
      wait-for-file /dev/disk/by-partuuid/30be395c-ef39-43d9-bc97-122e53f29dcc
      wait-for-file /dev/disk/by-partuuid/35567007-09f3-492d-860b-dcc61b974bc8
    '';
  };
 
  networking.hostName = "nixbeast";
  fileSystems = {
    "/" = {
      # Using the Btrfs filesystem UUID is the most robust method.
      device = "/dev/disk/by-uuid/f0916b95-2b4c-41d2-90e3-6e4c8d398f9d";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" "ssd" "space_cache=v2" "noatime" ];
    };
 
    "/home" = {
      device = "/dev/disk/by-uuid/f0916b95-2b4c-41d2-90e3-6e4c8d398f9d";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "ssd" "space_cache=v2" "noatime" ];
    };
 
    "/nix" = {
      device = "/dev/disk/by-uuid/f0916b95-2b4c-41d2-90e3-6e4c8d398f9d";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "ssd" "space_cache=v2" "noatime" ];
    };
 
    "/var" = { device = "/dev/disk/by-uuid/f0916b95-2b4c-41d2-90e3-6e4c8d398f9d"; fsType = "btrfs"; options = [ "subvol=@var" "compress=zstd" "ssd" "space_cache=v2" "noatime" ]; };
 
    # Using tmpfs for /tmp is generally recommended for performance and to avoid unnecessary writes.
    "/tmp" = { device = "tmpfs"; fsType = "tmpfs"; options = [ "defaults" "mode=1777" "size=32G" ]; };
 
    "/data" = { device = "/dev/disk/by-uuid/f0916b95-2b4c-41d2-90e3-6e4c8d398f9d"; fsType = "btrfs"; options = [ "subvol=@data" "nodatacow" "ssd" "space_cache=v2" "noatime" ]; };
 
    "/vm" = {
      device = "/dev/disk/by-uuid/f0916b95-2b4c-41d2-90e3-6e4c8d398f9d";
      fsType = "btrfs";
      # 'nodatacow' is critical for VM disk image performance.
      options = [ "subvol=@vm" "nodatacow" "ssd" "space_cache=v2" "noatime" ];
    };
 
    "/efi" = {
      device = "/dev/disk/by-partuuid/96a8b89f-0c2b-4cc5-828d-613d243ee696";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
 
    "/efi2" = {
      device = "/dev/disk/by-partuuid/afee2a35-efef-4eeb-ba66-eef96ae64912";
      fsType = "vfat";
      options = [ "noauto" "fmask=0077" "dmask=0077" ];
    };

  };

  # Using PARTUUIDs is a stable way to identify swap partitions.
  swapDevices = [
    { device = "/dev/disk/by-partuuid/df6b205b-82f5-48d9-8876-b132b6e0f383"; }
    { device = "/dev/disk/by-partuuid/64446512-5ea8-475e-9bff-4bb490472289"; }
  ];

}
