# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  networking.hostName = "nixbeast";
  boot = {
    loader.efi.efiSysMountPoint = "/efi";
    initrd.availableKernelModules = [ "nvme" "xhci_pci" "amdgpu" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [  ];
    supportedFilesystems = [ "zfs" ];
    zfs.forceImportRoot = true;
    # Tell initrd how to mount the root dataset
    #loader.systemd-boot.extraInstallCommands = ''
    #  set -euxo pipefail
    #  export PATH=${pkgs.coreutils}/bin:${pkgs.util-linux}/bin:${pkgs.rsync}/bin:$PATH
#
      # Mount secondary EFI partition
#      mkdir -p /mnt/efibackup
#      mount /dev/nvme1n1p1 /mnt/efibackup
#
      # Mirror contents
#      rsync -a --delete /boot/efi /mnt/efibackup/
#
#      umount /mnt/efibackup
#    '';
  };


  fileSystems = {
    "/" =
      { device = "rpool/ROOT/nixbeast";
        fsType = "zfs";
      };

    "/efi" = 
      { device = "/dev/disk/by-uuid/afee2a35-efef-4eeb-ba66-eef96ae64912";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };
      
    "/efi2" = 
      { device = "/dev/disk/by-uuid/96a8b89f-0c2b-4cc5-828d-613d243ee696";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };

    "/data" =
      { device = "rpool/data";
        fsType = "zfs";
      };

    "/home" =
      { device = "rpool/home";
        fsType = "zfs";
      };

    "/tmp" =
      { device = "rpool/tmp";
        fsType = "zfs";
      };

    "/var" =
      { device = "rpool/var";
        fsType = "zfs";
      };

    "/nix" =
      { device = "rpool/nix";
        fsType = "zfs";
      };

    "/vm" =
      { device = "rpool/vm";
        fsType = "zfs";
      };
  };

  swapDevices = [
    { device = "/dev/disk/by-partuuid/df6b205b-82f5-48d9-8876-b132b6e0f383"; }
    { device = "/dev/disk/by-partuuid/64446512-5ea8-475e-9bff-4bb490472289"; }
    { device = "/dev/disk/by-partuuid/fbaacb93-f630-42ae-927c-43b297902427"; }
  ];
  networking.hostId = "8425e349";

}
