# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  networking.hostName = "nixbeast";
  boot = {
    loader.efi.efiSysMountPoint = "/efi";
    initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [  ];
    supportedFilesystems = [ "zfs" ];
    zfs.forceImportRoot = true;
    # Tell initrd how to mount the root dataset
    #loader.systemd-boot.extraInstallCommands = ''
    #  set -euxo pipefail
    #  export PATH=${pkgs.coreutils}/bin:${pkgs.util-linux}/bin:${pkgs.rsync}/bin:$PATH
#
      # Mount secondary EFI partition
#      mkdir -p /mnt/efibackup
#      mount /dev/nvme1n1p1 /mnt/efibackup
#
      # Mirror contents
#      rsync -a --delete /boot/efi /mnt/efibackup/
#
#      umount /mnt/efibackup
#    '';
  };


  fileSystems = {
    "/" =
      { device = "rpool/ROOT/nixbeast";
        fsType = "zfs";
      };

    "/efi" = 
      { device = "/dev/disk/by-uuid/8ABD-4347";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };
      
    "/nix" =
      { device = "rpool/nix";
        fsType = "zfs";
      };

    "/data" =
      { device = "rpool/data";
        fsType = "zfs";
      };

    "/home" =
      { device = "rpool/home";
        fsType = "zfs";
      };

    "/var" =
      { device = "rpool/var";
        fsType = "zfs";
      };

    "/vm" =
      { device = "rpool/vm";
        fsType = "zfs";
      };
  };

  swapDevices = [
	{ device = "/dev/disk/by-uuid/1cc2eaa6-e42e-433a-84c8-38aeab5889b3"; }
	{ device = "/dev/disk/by-uuid/8d5018e9-6c0e-4590-9ee5-7f808908b4eb"; }
  ];
  networking.hostId = "8425e349";  

}
