# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  networking.hostName = "nixserve";
  boot = {
    loader.efi.efiSysMountPoint = "/efi";
    initrd.availableKernelModules = [ "nvme" "xhci_pci" "amdgpu" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [  ];
    supportedFilesystems = [ "zfs" ];
    zfs.forceImportRoot = true;
    # Tell initrd how to mount the root dataset
    #loader.systemd-boot.extraInstallCommands = ''
    #  set -euxo pipefail
    #  export PATH=${pkgs.coreutils}/bin:${pkgs.util-linux}/bin:${pkgs.rsync}/bin:$PATH
#
      # Mount secondary EFI partition
#      mkdir -p /mnt/efibackup
#      mount /dev/nvme1n1p1 /mnt/efibackup
#
      # Mirror contents
#      rsync -a --delete /boot/efi /mnt/efibackup/
#
#      umount /mnt/efibackup
#    '';
  };


  fileSystems = {
    "/" =
      { device = "rpool/nixserve";
        fsType = "zfs";
      };

    "/efi" = 
      { device = "/dev/disk/by-uuid/cfa5d431-4f85-49ef-acd0-995e31af4f80";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };
      
    "/nix" =
      { device = "rpool/nix";
        fsType = "zfs";
      };

    "/data" =
      { device = "rpool/data";
        fsType = "zfs";
      };

    "/home" =
      { device = "rpool/home";
        fsType = "zfs";
      };

    "/var" =
      { device = "rpool/var";
        fsType = "zfs";
      };

    "/tmp" =
      { device = "rpool/temp";
        fsType = "zfs";
      };

    "/vm" =
      { device = "rpool/vm";
        fsType = "zfs";
      };
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/450f8ae6-614e-4889-bdf2-47d44068bb70"; }
    { device = "/dev/disk/by-uuid/9f782b49-bcdf-4731-bb91-b8d5cede0943"; }
    { device = "/dev/disk/by-uuid/f826cfa5-e46e-4dce-a84e-03489f7b05ad"; }
  ];
  networking.hostId = "2b189654";  

}
